<?php

return [
    // The Telegram BOT api token
    'token' => env('TELEGRAM_BOT_TOKEN'),

    // Bot ID (extract from token)
    'bot_id' => (int) explode(':', env('TELEGRAM_BOT_TOKEN', ''))[0],

    // Service chat ID (forum chat for agents)
    'service_chat_id' => env('TELEGRAM_SERVICE_CHAT_ID'),

    // Webhook URL
    'webhook_url' => env('TELEGRAM_WEBHOOK_URL'),

    // Shared secret Telegram echoes back in the X-Telegram-Bot-Api-Secret-Token header
    'webhook_secret' => env('TELEGRAM_WEBHOOK_SECRET'),

    // Log channel
    'log_channel' => env('NUTGRAM_LOG_CHANNEL', 'null'),

    // if the webhook mode must validate the incoming IP range is from a telegram server
    'safe_mode' => env('APP_ENV', 'local') === 'production',

    // Extra or specific configurations
    'config' => [
        'client' => [
            'timeout' => 30,
            'connect_timeout' => 10,
        ],
    ],

    // Handlers are registered per request by App\Telegram\RegisterHandlers
    'routes' => false,

    // Enable or disable Nutgram mixins
    'mixins' => false,

    // Path to save files generated by nutgram:make command
    'namespace' => app_path('Telegram'),
];
